"use client";

import { useMemo, useState } from "react";
import { ChevronRight, CircleHelp, ExternalLink, Search, Sparkles, Target, Trophy, Users } from "lucide-react";

type Brand = {
  rank: number; name: string; chinese: string; type: string; color: string; tagline: string;
  edge: string; growth: string; outcome: string; evidence: string; url: string;
};

const brands: Brand[] = [
  { rank: 1, name: "New Oriental", chinese: "新东方雅思", type: "National education group", color: "#ef6a4b", tagline: "The scale benchmark", edge: "Trust built across generations, proprietary content and a nationwide offline + online network.", growth: "Cross-sells from a huge education ecosystem; brand search, referrals, centers and online courses compound each other.", outcome: "Standardized teacher training, QA systems, OMO data and a broad content operation make quality repeatable.", evidence: "75 schools · 1,534 learning centers · 44,200+ teachers (group-wide)", url: "https://investor.neworiental.org/zh-hans/corporate-profile" },
  { rank: 2, name: "New Channel", chinese: "新航道", type: "Test-prep specialist", color: "#d79a3b", tagline: "Small class, high-touch", edge: "A clear academic identity:精品小班 + full-course assistant + personalized service.", growth: "Founder authority, exam-focused content, school network, books and online courses feed one another.", outcome: "Detailed learning plans, assistant-led follow-up and repeatable course/teaching standards.", evidence: "Founded 2004 · IELTS, TOEFL, SAT, GRE and more · national school network", url: "https://www.xhd.cn/about" },
  { rank: 3, name: "Global Education", chinese: "环球教育 / 环球雅思", type: "IELTS chain", color: "#2d8f83", tagline: "The legacy IELTS chain", edge: "A long-running IELTS identity with a recognizable teaching system and broad local presence.", growth: "City-by-city centers, partner footprint, IELTS SEO and a wide course ladder.", outcome: "Entry tests, progress tracking, structured levels and standardized service routines.", evidence: "Founded 1997 · 150+ centers in 100+ cities claimed on official site", url: "https://www.gedu.org/" },
  { rank: 4, name: "Longre Education", chinese: "朗阁教育", type: "Overseas exam chain", color: "#7657a6", tagline: "Specialist network", edge: "Exam specialization plus a dense multi-city teaching network and self-published materials.", growth: "Local campuses, high-intent exam search, closed camps and a full overseas-test portfolio.", outcome: "Band-based programs, intensive camps, writing/speaking add-ons and teacher resources.", evidence: "60+ campuses · 36 cities · 100,000 learners/year (public brand profile)", url: "https://www.jiaoyubao.cn/brand/lgjy/" },
  { rank: 5, name: "Guixue Education", chinese: "学为贵", type: "Methodology-led brand", color: "#0f6b57", tagline: "Closest DOL analogue", edge: "GETS / 真经 methodology, founder intellectual property, books and teacher-led authority.", growth: "Founder content, campus seminars, books, apps, online classes and overseas planning create a funnel.", outcome: "GETS framework, diagnostic testing, closed camps and one-to-one speaking/writing feedback.", evidence: "20+ cities · 100+ service centers · IELTS Platinum partner", url: "https://a.guixue.com/about/" },
  { rank: 6, name: "EIC Test Prep", chinese: "启德考培", type: "Study-abroad funnel", color: "#3f78b5", tagline: "Score to study-abroad pipeline", edge: "IELTS is embedded in a wider study-abroad planning and application ecosystem.", growth: "Lead generation from overseas counseling, local campuses, mock tests and owned learning tools.", outcome: "Online assessment, full mock exams, reports, practice systems and advisor follow-up.", evidence: "16 branches · 32 flagship campuses (public company material)", url: "https://www.eickaopei.com/" },
  { rank: 7, name: "Shinyway", chinese: "新通考培", type: "International education group", color: "#c26078", tagline: "Regional depth + global reach", edge: "Long operating history and a trusted education brand rooted in Hangzhou and East China.", growth: "Multi-city branches plus overseas offices; language prep cross-sells with study-abroad planning.", outcome: "Personalized plans, experienced counselors and integrated test-prep / application service.", evidence: "Founded 1996 · 20+ mainland cities and overseas offices", url: "https://www.igo.cn/campus/" },
  { rank: 8, name: "Xiaozhan Education", chinese: "小站教育", type: "Online-first test prep", color: "#487d88", tagline: "Digital tutoring at scale", edge: "Online live 1:1 / small-group teaching, community and learning tools packaged together.", growth: "Content and community lower acquisition friction; online delivery expands beyond local campuses.", outcome: "Teacher matching, online follow-up, mock tools and data-enabled practice.", evidence: "10M+ registered users · 150K paid learners claimed by brand", url: "https://www.zhan.com/aboutus/aboutus" },
  { rank: 9, name: "IELTS Bro", chinese: "雅思哥", type: "Content + app brand", color: "#ee8c42", tagline: "Exam intelligence layer", edge: "A product-led brand built on question banks, current speaking topics, mock exams and community trust.", growth: "Free app utility and exam content create massive top-of-funnel reach before paid courses.", outcome: "High-frequency practice, simulated computer tests, AI feedback and teacher-led courses.", evidence: "10M+ cumulative users · 300K+ annual course attendance claimed", url: "https://ieltsbro.com/" },
  { rank: 10, name: "Gaotu / Todo IELTS", chinese: "高途雅思 / 土豆雅思", type: "Teacher-IP edtech", color: "#9a5fba", tagline: "Livestream + AI engine", edge: "Star teachers, livestream learning, AI speaking tools and a systemized product catalog.", growth: "Social content and low-friction online acquisition convert into cohort courses and memberships.", outcome: "Diagnostic tools, AI practice, teaching-research loops and assistant support.", evidence: "Gaotu education group · proprietary IELTS content and AI tools", url: "https://www.todoen.com/" },
];

const axes = [
  { id: "edge", short: "Lợi thế cạnh tranh", label: "Why they win", prompt: "Họ được nhớ đến vì điều gì và điều đó khó sao chép ra sao?", icon: Trophy },
  { id: "growth", short: "Growth engine", label: "How they grow", prompt: "Họ biến sự chú ý thành học viên trả tiền bằng kênh nào?", icon: Users },
  { id: "outcome", short: "Bằng chứng kết quả", label: "How they prove it", prompt: "Họ biến việc học thành kết quả có thể đo và nhân rộng thế nào?", icon: Target },
] as const;

export default function Home() {
  const [query, setQuery] = useState("");
  const [activeAxis, setActiveAxis] = useState<"edge" | "growth" | "outcome">("edge");
  const [selected, setSelected] = useState<Brand>(brands[4]);
  const filtered = useMemo(() => brands.filter((b) => `${b.name} ${b.chinese} ${b.type}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const active = axes.find((a) => a.id === activeAxis)!;
  return <main className="min-h-screen bg-[#f6f8f7] text-[#13231f]">
    <header className="border-b border-[#dbe5e1] bg-[#f6f8f7]/95 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#13231f] text-[#f4d7a1]"><Sparkles className="h-5 w-5" /></div><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#0f6b57]">Nemo12 research lab</p><p className="font-semibold">China IELTS benchmark</p></div></div><span className="hidden rounded-full border border-[#d4e0db] bg-white px-3 py-1.5 text-xs text-[#6b7d76] sm:block">Updated · 26 Sep 2026</span></div></header>
    <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10 lg:py-12">
      <section className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.17em] text-[#0f6b57]">Competitive intelligence</p><h1 className="max-w-4xl font-serif text-5xl font-semibold leading-[.98] tracking-[-.045em] sm:text-6xl">What should Nemo12 learn from China’s IELTS leaders?</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#5e716a]">Một workspace để so sánh 10 thương hiệu theo ba câu hỏi quyết định: họ thắng vì gì, tăng trưởng bằng cách nào, và chứng minh kết quả ra sao.</p></div><div className="rounded-2xl bg-[#153f36] p-6 text-white shadow-[0_20px_50px_rgba(21,63,54,.18)]"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#b9d8ce]">Working thesis</p><p className="mt-3 font-serif text-2xl leading-tight">“Closest DOL analogue” của Trung Quốc là 学为贵 — nhưng Nemo12 cần học cả engine phân phối lẫn hệ thống outcome.</p><p className="mt-5 text-sm leading-6 text-[#d5e9e3]">Dùng tab bên dưới để đọc theo từng lens, sau đó mở từng brand để ghi lại ý tưởng có thể thử.</p></div></section>
      <section className="mt-10 grid gap-3 md:grid-cols-3">{axes.map((axis, i) => { const Icon = axis.icon; const on = activeAxis === axis.id; return <button key={axis.id} onClick={() => setActiveAxis(axis.id)} className={`group rounded-2xl border p-5 text-left transition ${on ? "border-[#0f6b57] bg-white shadow-[0_8px_30px_rgba(15,107,87,.10)]" : "border-[#dbe5e1] bg-[#fbfcfb] hover:border-[#9fbdb3]"}`}><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${on ? "bg-[#dceee8] text-[#0f6b57]" : "bg-[#edf2f0] text-[#70817a]"}`}><Icon className="h-5 w-5" /></span><ChevronRight className={`h-5 w-5 transition ${on ? "text-[#0f6b57]" : "text-[#b6c2be] group-hover:translate-x-1"}`} /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-[#81918b]">0{i + 1}</p><h2 className="mt-1 text-xl font-bold">{axis.short}</h2><p className="mt-2 text-sm leading-6 text-[#667872]">{axis.prompt}</p></button> })}</section>
      <section className="mt-10 grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px] lg:items-start"><div><div className="mb-4 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-[#0f6b57]">Lens {activeAxis === "edge" ? "01" : activeAxis === "growth" ? "02" : "03"}</p><h2 className="mt-1 font-serif text-3xl font-semibold">{active.label}</h2></div><label className="relative block sm:w-64"><Search className="absolute left-3 top-3 h-4 w-4 text-[#84948e]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm brand…" className="w-full rounded-xl border border-[#dbe5e1] bg-white py-2.5 pl-9 pr-3 text-sm outline-none ring-[#0f6b57] focus:ring-2" /></label></div><div className="space-y-3">{filtered.map((b) => <button key={b.name} onClick={() => setSelected(b)} className={`group grid w-full gap-4 rounded-2xl border bg-white p-5 text-left transition sm:grid-cols-[58px_1fr_1.35fr] sm:items-start ${selected.name === b.name ? "border-[#0f6b57] shadow-[0_10px_28px_rgba(15,107,87,.09)]" : "border-[#dbe5e1] hover:-translate-y-0.5 hover:border-[#a5bbb4]"}`}><div className="grid h-12 w-12 place-items-center rounded-2xl text-lg font-bold text-white" style={{ backgroundColor: b.color }}>{b.rank}</div><div><h3 className="font-bold">{b.name}</h3><p className="mt-1 text-sm font-medium text-[#0f6b57]">{b.chinese}</p><span className="mt-3 inline-flex rounded-full bg-[#f0f4f2] px-2.5 py-1 text-[11px] font-semibold text-[#6d7f78]">{b.type}</span></div><div><p className="text-base leading-7 text-[#324942]">{b[activeAxis]}</p><p className="mt-3 text-xs font-bold uppercase tracking-[.13em] text-[#9aa8a3]">{b.tagline}</p></div></button>)}</div></div>
        <aside className="sticky top-5 rounded-2xl border border-[#dbe5e1] bg-white p-6 shadow-[0_12px_35px_rgba(19,35,31,.06)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#81918b]">Selected brand · #{selected.rank}</p><h2 className="mt-2 font-serif text-3xl font-semibold leading-tight">{selected.name}</h2><p className="mt-1 font-medium text-[#0f6b57]">{selected.chinese}</p></div><div className="grid h-11 w-11 place-items-center rounded-2xl text-lg font-bold text-white" style={{ backgroundColor: selected.color }}>{selected.rank}</div></div><p className="mt-5 rounded-xl bg-[#f4f8f6] p-4 text-sm font-semibold leading-6 text-[#38564d]">{selected.tagline}</p><div className="mt-6 space-y-5">{axes.map((axis, i) => <div key={axis.id}><div className="flex items-center gap-2"><span className="text-[11px] font-bold text-[#0f6b57]">0{i + 1}</span><p className="text-xs font-bold uppercase tracking-[.12em] text-[#81918b]">{axis.short}</p></div><p className="mt-2 text-sm leading-6 text-[#536862]">{selected[axis.id]}</p></div>)}</div><div className="mt-6 border-t border-[#e4ebe8] pt-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#81918b]">Research evidence</p><p className="mt-2 text-sm leading-6 text-[#536862]">{selected.evidence}</p><a href={selected.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#0f6b57] hover:underline">Open source <ExternalLink className="h-4 w-4" /></a></div></aside>
      </section>
      <section className="mt-12 rounded-2xl border border-[#dbe5e1] bg-[#fffdf8] p-6 lg:p-8"><div className="flex items-start gap-3"><CircleHelp className="mt-1 h-5 w-5 shrink-0 text-[#c58c2e]" /><div><h2 className="font-serif text-2xl font-semibold">Research brief cho Nemo12</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5f6e68]">Mỗi lần benchmark một brand, hãy ép mình trả lời ba câu hỏi này bằng bằng chứng, không bằng cảm giác.</p><div className="mt-6 grid gap-3 md:grid-cols-3">{["Họ thắng nhờ điều gì mà Nemo12 có thể biến thành IP?", "Họ biến attention thành paid learner bằng funnel nào?", "Họ chứng minh outcome và làm outcome lặp lại thế nào?"].map((q, i) => <div key={q} className="rounded-xl border border-[#eadfca] bg-white p-4"><span className="text-xs font-bold text-[#c58c2e]">0{i + 1}</span><p className="mt-2 text-sm font-semibold leading-6 text-[#3c4f47]">{q}</p></div>)}</div></div></div></section>
      <footer className="flex flex-col justify-between gap-3 py-8 text-xs text-[#899892] sm:flex-row"><span>Nemo12 · China IELTS benchmark workspace</span><span>Public sources · Claims should be verified before investment decisions</span></footer>
    </div>
  </main>;
}
