import type { TargetType } from "@/lib/targets";

export const PLAYBOOKS: Record<TargetType, { thesis: string; jobs: { functional: string[]; emotional: string[]; social: string[] }; offer: string; includes: string[]; criteria: string[] }> = {
  Experts: { thesis: "Hợp tác với influencer tiếng Anh/IELTS có trust thật để tạo awareness, referral và trials — không chỉ mua endorsement.", jobs: { functional: ["Mang Nemo12 đến đúng learners", "Tạo content hoặc format học tiếng Anh hữu ích", "Kéo audience vào trial có tracking"], emotional: ["Giữ uy tín với audience", "Không bị biến thành quảng cáo lộ liễu", "Có thêm content/value đáng tin"], social: ["Củng cố vị thế English/IELTS influencer", "Gắn tên với learner outcomes", "Mở rộng network giáo dục"] }, offer: "Nemo12 × English/IELTS Influencer Partnership", includes: ["Co-created content hoặc challenge", "Referral link và dashboard trials", "Expert-led debrief / learner insight"], criteria: ["Audience đúng nhóm học tiếng Anh/IELTS", "Engagement và trust có bằng chứng", "Content quality phù hợp Nemo12", "Sẵn sàng đo referral/trials"] },
  "Professional Affiliators": { thesis: "Tạo referral có tracking và incentive minh bạch.", jobs: { functional: ["Có offer dễ giới thiệu", "Theo dõi referral rõ ràng", "Tạo thêm thu nhập hoặc value cho audience"], emotional: ["Tin offer không ảnh hưởng uy tín", "Dễ bắt đầu", "Thấy kết quả minh bạch"] , social: ["Được nhìn nhận là người giới thiệu có chọn lọc", "Mở rộng network giáo dục", "Tạo case study hiệu quả"] }, offer: "Nemo12 Referral Partnership", includes: ["Referral link", "Dashboard kết quả", "Cơ chế reward minh bạch"], criteria: ["Audience phù hợp", "Kênh promotion xác minh được", "Có lịch sử referral", "Brand-safe và minh bạch"] },
  "Nemo12 Advocates": { thesis: "Biến sự yêu thích Nemo12 thành referral và word-of-mouth có thể đo lường.", jobs: { functional: ["Giới thiệu Nemo12 cho phụ huynh/học sinh phù hợp", "Chia sẻ trải nghiệm thật", "Tham gia hoạt động cộng đồng nhẹ nhàng"] , emotional: ["Thấy con/em mình tiến bộ", "Tự hào khi giới thiệu điều hữu ích", "Không cảm thấy bị ép bán hàng"] , social: ["Được công nhận là thành viên tích cực", "Kết nối với các gia đình/học sinh khác", "Cùng xây cộng đồng Nemo12"] }, offer: "Nemo12 Advocate Referral Program", includes: ["Personal referral link", "Reward hoặc benefit minh bạch", "Community spotlight / advocate story"] , criteria: ["Parent hoặc student đang gắn bó với Nemo12", "Có trải nghiệm tích cực có thể xác minh", "Sẵn sàng giới thiệu tự nguyện", "Đồng ý tracking referral"] },
  Schools: { thesis: "Cho trường một outcome học sinh nhìn thấy ngay, không bắt đầu bằng bán khóa học.", jobs: { functional: ["Biết gap IELTS theo kỹ năng", "Có dữ liệu để tư vấn học tập", "Thêm hoạt động cho học sinh"] , emotional: ["Yên tâm assessment đáng tin", "Giảm áp lực chọn giải pháp", "Tự hào về chăm sóc học sinh"] , social: ["Chứng minh student outcomes", "Tăng uy tín với phụ huynh", "Thể hiện đổi mới giáo dục"] }, offer: "Free IELTS Diagnostic for 100 Students", includes: ["100 trial seats", "Cohort gap report", "Workshop đọc kết quả"] , criteria: ["Có 100+ learners phù hợp", "Có owner rõ ràng", "Có kênh phân phối nội bộ", "Cam kết follow-up", "Không xung đột assessment"] },
  Communities: { thesis: "Cung cấp utility cộng đồng có thể co-brand và đo được.", jobs: { functional: ["Tạo member benefit", "Kéo tương tác chất lượng", "Hiểu nhu cầu thành viên"] , emotional: ["Tin rằng partner không spam", "Dễ tổ chức", "Thấy thành viên được giúp thật"] , social: ["Củng cố vai trò community builder", "Tăng uy tín với member", "Tạo case study cho cộng đồng"] }, offer: "Community Diagnostic Week", includes: ["Landing page co-brand", "Tracking trials theo source", "Community insight report"] , criteria: ["Member fit còn hoạt động", "Sở hữu kênh phân phối", "Community lead chịu trách nhiệm", "Chấp nhận đo trials"] },
};

export const CADENCE: Array<{period:string;metric:string;tasks:string[]}> = [];
/*
export const CADENCE = [
  { period: "Ngày", metric: "5 quality outreaches", tasks: ["Research + qualify 5 targets", "Gửi 5 outreach cá nhân hóa", "Follow-up mọi phản hồi <24h"] },
  { period: "Tuần", metric: "25 conversations", tasks: ["Mở 25 meaningful conversations", "Chốt 2 activation có ngày chạy", "Review trials theo source và nhóm"] },
  { period: "Tháng", metric: "500 trials", tasks: ["Tạo 500 trials từ partners", "Chạy 4 pilots kèm cohort report", "Sửa hoặc dừng playbook không tạo trials"] },
  { period: "Quý", metric: "2.000 trials", tasks: ["Đạt 2.000 partner-sourced trials", "Chuyển 10 pilots thành repeat partners", "Xuất bản 1 data asset để mở distribution"] },
]; */
