import type { TargetType } from "@/lib/targets";

export const PLAYBOOKS: Record<TargetType, { thesis: string; jobs: { functional: string[]; emotional: string[]; social: string[] }; offer: string; includes: string[]; criteria: string[] }> = {
  Experts: { thesis: "Mượn expertise để tăng trust — không mua endorsement.", jobs: { functional: ["Đưa chuyên môn đến đúng learners", "Kiểm chứng framework đánh giá", "Tạo nội dung có bằng chứng"], emotional: ["Thấy đóng góp có ý nghĩa", "Yên tâm về chuẩn học thuật", "Được tôn trọng chuyên môn"], social: ["Củng cố vai trò thought leader", "Kết nối với peer uy tín", "Gắn tên với tác động giáo dục"] }, offer: "Nemo12 Expert Council", includes: ["Review framework 45 phút", "Đồng tác giả insight report", "Expert profile hoặc webinar"], criteria: ["Chuyên môn có thể xác minh", "Ảnh hưởng đúng learners/peers", "Triết lý học tập phù hợp", "Sẵn sàng co-create"] },
  Creators: { thesis: "Biến product experience thành nội dung mà audience muốn tham gia.", jobs: { functional: ["Tạo format nội dung mới", "Tăng tương tác có đo lường", "Đem utility thật cho audience"], emotional: ["Tự tin không quảng cáo lố", "Hứng thú với thử thách mới", "An tâm bảo vệ uy tín"] , social: ["Được nhìn nhận là creator có ích", "Tạo câu chuyện audience cùng tham gia", "Mở rộng network giáo dục"] }, offer: "Creator × Nemo12 Trial Challenge", includes: ["Challenge có tracking link", "Dashboard kết quả audience", "Nội dung debrief cùng expert"], criteria: ["Audience 15–24 phù hợp", "Engagement thật", "Nội dung học tập/self-growth", "Brand-safe và minh bạch"] },
  Alumni: { thesis: "Kích hoạt tinh thần give-back qua một hoạt động cụ thể, nhẹ vận hành.", jobs: { functional: ["Tạo hoạt động alumni–student", "Mang mentor và cơ hội về trường", "Đo impact của chapter"] , emotional: ["Tự hào được đóng góp", "Cảm thấy vẫn thuộc về cộng đồng", "Dễ bắt đầu mà không quá tải"] , social: ["Thể hiện chapter năng động", "Kết nối các thế hệ", "Tạo uy tín với trường"] }, offer: "Alumni Give-back Diagnostic Day", includes: ["100 diagnostic miễn phí", "Alumni mentor debrief", "Impact report cho chapter"] , criteria: ["Network còn hoạt động", "Có access tới learners", "Có internal champion", "Đã từng mentoring/give-back"] },
  Schools: { thesis: "Cho trường một outcome học sinh nhìn thấy ngay, không bắt đầu bằng bán khóa học.", jobs: { functional: ["Biết gap IELTS theo kỹ năng", "Có dữ liệu để tư vấn học tập", "Thêm hoạt động cho học sinh"] , emotional: ["Yên tâm assessment đáng tin", "Giảm áp lực chọn giải pháp", "Tự hào về chăm sóc học sinh"] , social: ["Chứng minh student outcomes", "Tăng uy tín với phụ huynh", "Thể hiện đổi mới giáo dục"] }, offer: "Free IELTS Diagnostic for 100 Students", includes: ["100 trial seats", "Cohort gap report", "Workshop đọc kết quả"] , criteria: ["Có 100+ learners phù hợp", "Có owner rõ ràng", "Có kênh phân phối nội bộ", "Cam kết follow-up", "Không xung đột assessment"] },
  Communities: { thesis: "Cung cấp utility cộng đồng có thể co-brand và đo được.", jobs: { functional: ["Tạo member benefit", "Kéo tương tác chất lượng", "Hiểu nhu cầu thành viên"] , emotional: ["Tin rằng partner không spam", "Dễ tổ chức", "Thấy thành viên được giúp thật"] , social: ["Củng cố vai trò community builder", "Tăng uy tín với member", "Tạo case study cho cộng đồng"] }, offer: "Community Diagnostic Week", includes: ["Landing page co-brand", "Tracking trials theo source", "Community insight report"] , criteria: ["Member fit còn hoạt động", "Sở hữu kênh phân phối", "Community lead chịu trách nhiệm", "Chấp nhận đo trials"] },
  Media: { thesis: "Pitch dữ liệu và câu chuyện công chúng quan tâm, không pitch product launch.", jobs: { functional: ["Có dữ liệu độc quyền", "Tìm góc bài đúng thời điểm", "Tiếp cận nguồn chuyên gia"] , emotional: ["Tin methodology", "An tâm không bị PR hóa", "Hứng thú với insight mới"] , social: ["Tạo tác phẩm có ảnh hưởng", "Củng cố beat giáo dục", "Được trích dẫn bởi cộng đồng"] }, offer: "Vietnam Learner Gap Index", includes: ["Dataset ẩn danh", "Expert commentary", "Biểu đồ và local cuts"] , criteria: ["Có education/youth beat", "Ưu tiên data-led story", "Reach đúng phụ huynh/learners", "Editorial fit rõ"] },
};

export const CADENCE = [
  { period: "Ngày", metric: "5 quality outreaches", tasks: ["Research + qualify 5 targets", "Gửi 5 outreach cá nhân hóa", "Follow-up mọi phản hồi <24h"] },
  { period: "Tuần", metric: "25 conversations", tasks: ["Mở 25 meaningful conversations", "Chốt 2 activation có ngày chạy", "Review trials theo source và nhóm"] },
  { period: "Tháng", metric: "500 trials", tasks: ["Tạo 500 trials từ partners", "Chạy 4 pilots kèm cohort report", "Sửa hoặc dừng playbook không tạo trials"] },
  { period: "Quý", metric: "2.000 trials", tasks: ["Đạt 2.000 partner-sourced trials", "Chuyển 10 pilots thành repeat partners", "Xuất bản 1 data asset để mở distribution"] },
];
