import type { OutreachTarget, TargetType } from "@/lib/targets";

type Candidate = [name: string, type: Exclude<TargetType, "Nemo12 Advocates">, city: string, website: string, summary: string];

// Public-source candidate pool. These are intentionally Research, not Qualified, until a second source and contact route are verified.
const candidates: Candidate[] = [
  ["Khánh Vy", "Experts", "Hà Nội", "https://www.youtube.com/@KhanhVyOfficial", "English-learning creator; verify current audience and partnership route."],
  ["Hồ Kính Đạt / IELTS with Datio", "Experts", "TP.HCM", "https://ieltsdatio.edu.vn/", "IELTS educator and creator with public channels; verify collaboration fit."],
  ["Nguyễn Ngọc Bách", "Experts", "Hà Nội", "https://ieltsngocbach.com/", "IELTS educator with public learning community; verify current activity."],
  ["Đặng Trần Tùng", "Experts", "Hà Nội", "https://theieltsworkshop.com/", "IELTS educator/creator; verify public partnership contact."],
  ["Nguyễn Lâm Thảo Tâm", "Experts", "TP.HCM", "https://www.facebook.com/thaotamnguyenlam/", "English-speaking creator profile; verify English-learning audience fit."],
  ["Hana's Lexis", "Experts", "TP.HCM", "https://www.youtube.com/@HanasLexis", "English-learning creator; verify audience and business route."],
  ["Dương Kiều Oanh", "Experts", "Hà Nội", "https://www.facebook.com/", "IELTS teacher candidate from public education listings; source verification required."],
  ["IELTS with Datio", "Experts", "TP.HCM", "https://www.youtube.com/@IELTSwithDatio", "IELTS content channel; verify owner and current reach."],
  ["IELTS Face-Off educators", "Experts", "Hà Nội", "https://ielts.ican.vn/ifo", "English/IELTS education talent pool; identify individual public contacts."],
  ["VTV7 English educators", "Experts", "Hà Nội", "https://vtv.vn/english-by-stories.html", "English education content network; identify individual creators."],
  ["British Council IELTS Affiliate", "Professional Affiliators", "Toàn quốc", "https://www.britishcouncil.vn/en/exam/ielts-affiliate-programme", "Official affiliate programme; operator/team, not a person."],
  ["E2Language Affiliate", "Professional Affiliators", "Toàn quốc", "https://www.e2language.com/pages/affiliate-partnerships", "English test-prep affiliate programme; verify Vietnam route."],
  ["ELSA Speak Affiliate Vietnam", "Professional Affiliators", "Toàn quốc", "https://elsaspeak.vn/affiliate-program-ielts9/", "Public affiliate programme with tracking/commission information."],
  ["PTE APAC Education Affiliate", "Professional Affiliators", "Toàn quốc", "https://pteapac.edu.vn/affiliate_program", "Public education affiliate programme; verify English/IELTS overlap."],
  ["PrepRoadRunner Partner Program", "Professional Affiliators", "Toàn quốc", "https://www.preproadrunner.com/en/affiliate-program", "Partner programme for IELTS educators, creators and communities."],
  ["UBEST Affiliate Program", "Professional Affiliators", "Toàn quốc", "https://ubest.edu.vn/p/affiliate-program", "Public affiliate programme; verify current operating status."],
  ["Amslink Franchise / Partnership", "Professional Affiliators", "Hà Nội", "https://nhuongquyen.amslink.edu.vn/", "Public partnership route; likely organization/team, not individual."],
  ["WISE English referral community", "Professional Affiliators", "Toàn quốc", "https://wiseenglish.edu.vn/en/loyal-customers", "Public referral signal; verify whether external referrals are accepted."],
  ["IDP IELTS partner development", "Professional Affiliators", "Toàn quốc", "https://ielts.idp.com/vietnam/partners", "Official partner route; verify whether non-competing referral partners qualify."],
  ["IELTS Vietnam partnership route", "Professional Affiliators", "Toàn quốc", "https://ieltsvietnam.edu.vn/chuyen-giao/", "Public partnership/contact route; verify current offer."],
  ["THPT Chuyên Hà Nội – Amsterdam", "Schools", "Hà Nội", "https://hn-ams.edu.vn/", "Public school contact and English-related activity; verify decision maker."],
  ["THPT Chuyên Ngoại ngữ – ĐHQGHN", "Schools", "Hà Nội", "https://flss.vnu.edu.vn/", "English-focused school with IELTS-oriented language pathway."],
  ["THPT Chuyên ĐH Sư phạm Hà Nội", "Schools", "Hà Nội", "https://chuyensp.edu.vn/", "High-achieving school; verify English programme and access route."],
  ["UNIS Hanoi", "Schools", "Hà Nội", "https://www.unishanoi.org/", "English-language school with public admissions and EAL routes."],
  ["Vinschool", "Schools", "Hà Nội", "https://vinschool.edu.vn/", "Large school system with English programme; verify partnership owner."],
  ["Phổ thông Năng khiếu – ĐHQG-HCM", "Schools", "TP.HCM", "https://ptnk.edu.vn/", "Selective school; verify English/IELTS activity and contact route."],
  ["THPT Chuyên Lê Hồng Phong", "Schools", "TP.HCM", "https://lehongphong.edu.vn/", "Selective school; verify English programme and decision maker."],
  ["THPT Chuyên Trần Đại Nghĩa", "Schools", "TP.HCM", "https://trandainghia.edu.vn/", "Selective school; verify English/IELTS access."],
  ["Horizon International Bilingual School", "Schools", "Hà Nội / TP.HCM", "https://www.horizon.edu.vn/", "Bilingual school with public IELTS preparation signal."],
  ["RMIT Vietnam School of English", "Schools", "TP.HCM / Hà Nội", "https://www.rmit.edu.vn/", "English and pathway programmes; verify Nemo12 partnership fit."],
  ["VietAbroader", "Communities", "Toàn quốc", "https://vietabroader.org/", "Education/study-abroad community; verify current activity and lead."],
  ["AIESEC in Vietnam", "Communities", "Toàn quốc", "https://www.aiesec.vn/", "Youth network with public partnership route."],
  ["YBOX.VN", "Communities", "Toàn quốc", "https://ybox.vn/hop-tac/hop-tac-cung-ybox-227087", "Youth opportunity community with public collaboration route."],
  ["VietSeeds", "Communities", "Toàn quốc", "https://vietseeds.org/", "Scholarship/community organisation; verify learner distribution route."],
  ["VNU Youth", "Communities", "Hà Nội", "https://youth.vnu.edu.vn/", "University youth network; verify current programme lead."],
  ["RMIT Student Council", "Communities", "TP.HCM / Hà Nội", "https://www.rmit.edu.vn/students/campus-life", "Student community route; verify activity owner."],
  ["Canadian International School Vietnam", "Schools", "TP.HCM", "https://www.cis.edu.vn/", "International school with English-medium learning; verify partnership owner."],
  ["British International School Ho Chi Minh City", "Schools", "TP.HCM", "https://www.nordangliaeducation.com/bis-hcmc", "English-medium international school; verify learner access and contact route."],
  ["Fulbright Student Engagement", "Communities", "TP.HCM", "https://fulbright.edu.vn/student-engagement/", "Student community and engagement route."],
  ["VinUni Student Clubs", "Communities", "Hà Nội", "https://vinuni.edu.vn/student-life/clubs-and-organizations/", "Student clubs with public organisation page."],
  ["SVUK", "Communities", "Toàn quốc", "https://svuk.org.uk/", "Vietnamese student community abroad; verify Vietnam learner access."],
  ["Enactus Vietnam", "Communities", "Toàn quốc", "https://enactus.org/country/vietnam/", "Student entrepreneurship network; verify active Vietnam contact."],
  ["THPT Chuyên Trần Phú", "Schools", "Hải Phòng", "https://thptchuyentranphu.haiphong.edu.vn/", "Selective high school; verify English programme and decision maker."],
  ["THPT Hàng Hải", "Schools", "Hải Phòng", "https://thpthanghai.edu.vn/", "Public high school with public school profile; verify English access."],
  ["Ngôi Sao Hà Nội – Hải Phòng Campus", "Schools", "Hải Phòng", "https://ngoisaohaiphong.edu.vn/", "High school programme with IELTS 7.0+ target."],
  ["THPT Nguyễn Trãi Hải Phòng", "Schools", "Hải Phòng", "https://thptchuyennguyentrai.haiphong.edu.vn/", "Selective school candidate; verify current English activity."],
  ["THPT Thái Phiên Hải Phòng", "Schools", "Hải Phòng", "https://thptthaiphien.haiphong.edu.vn/", "Public school candidate; verify English programme and contact."],
  ["Đại học Hải Phòng", "Schools", "Hải Phòng", "https://dhhp.edu.vn/", "University with public English/IELTS outcomes; verify learner access."],
  ["Hải Phòng English Campus", "Communities", "Hải Phòng", "https://haiphongenglishhomestay.com/cong-dong/", "Public English community and IELTS activity; verify community lead."],
  ["Hải Phòng Youth Union", "Communities", "Hải Phòng", "https://thanhdoanhaiphong.gov.vn/", "Youth distribution route; verify English/education programme fit."],
  ["Hai Phong Student Association", "Communities", "Hải Phòng", "https://hoisinhvienhaiphong.org.vn/", "Student network candidate; verify active contact."],
  ["HP English learner groups", "Communities", "Hải Phòng", "https://www.haiphong.edu.vn/", "Public education directory signal; identify active English community."],
  ["THPT Chuyên Lê Quý Đôn Đà Nẵng", "Schools", "Đà Nẵng", "https://thpt-lequydon-danang.edu.vn/", "Selective high school; verify English/IELTS programme."],
  ["THPT Quang Trung Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "Official education directory listing; verify contact and programme."],
  ["THPT Khai Trí Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "Official education directory listing; verify English access."],
  ["Sky-line Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "Bilingual school listing; verify partnership owner."],
  ["Olympia Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "Bilingual school listing; verify English learner access."],
  ["APU International School Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "International school listing; verify decision maker."],
  ["Singapore International School Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "International school listing; verify programme fit."],
  ["FPT School Đà Nẵng", "Schools", "Đà Nẵng", "https://danang.edu.vn/DsDonViGiaoDuc?caphoc=THPT&tuthuc=1", "School listing with English learner access; verify contact."],
  ["Đà Nẵng Student Association", "Communities", "Đà Nẵng", "https://hoisinhvien.vn/", "Student distribution route; verify city-level English/education activity."],
  ["Đà Nẵng Youth Union", "Communities", "Đà Nẵng", "https://doanthanhnien.vn/", "Youth distribution route; verify city-level programme lead."],
];

function slug(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }

export const RESEARCH_CANDIDATES: OutreachTarget[] = candidates.map(([name, type, city, website, researchSummary], index) => ({
  id: `research-${slug(type)}-${slug(name)}-${index}`, name, type, entityType: type === "Experts" ? "Person" : type === "Professional Affiliators" ? (/[Pp]rogram|[Pp]artner|[Aa]ffiliate|[Rr]eferral|[Ff]ranchise|[Rr]oute|[Dd]evelopment/.test(name) ? "Organization" : "Person") : "Organization", relationshipType: type === "Schools" ? "Distribution" : type === "Communities" ? "Community activation" : "Referral", organization: "", location: city, city, website,
  audience: "", audienceSizeEstimate: "", audienceFit: "", expertiseArea: type === "Experts" ? "English / IELTS" : "", platforms: "", contentTopics: "", promotionChannel: type === "Professional Affiliators" ? "Referral / affiliate route" : "", organizationType: type === "Schools" ? "School" : type === "Communities" ? "Community" : "", organizationSize: "", decisionMakerRole: "", distributionChannels: "", accessToLearners: "", engagementQuality: "", influenceType: type === "Experts" ? "English/IELTS influencer" : "", partnershipReadiness: "Needs verification", researchConfidence: "Low",
  facebookUrl: "", linkedinUrl: "", contactRole: "", contactChannel: "Public source; contact route to verify", contactEmail: "", contactPhone: "", contactFormUrl: "", preferredContactMethod: "", contactStatus: "Research needed", warmContactPerson: "", warmContactTeam: "", warmContactNote: "", relationshipStrength: "Cold", introductionStatus: "Not requested", sourceUrls: website, researchSummary: `FACT — ${researchSummary} INFERENCE — fit, audience quality, decision-maker, and partnership readiness are not yet verified.`, advocateType: "", valueProp: "", nextAction: "Verify second source, public contact route, and fit rubric.", nextActionDate: "Chưa đặt", stage: "Research", fit: 0, access: 0, trust: 0, readiness: 0, score: 0, trials: 0, learners: 0, notes: "Candidate sourced from a public website; not qualified yet.", updatedAt: new Date().toISOString(),
}));
