export const TARGET_TYPES = ["School", "Community", "University", "NGO", "Media"] as const;
export const STAGES = ["Research", "Qualified", "Contacted", "Replied", "Conversation", "Meeting", "Pilot", "Partner"] as const;
export type TargetType = typeof TARGET_TYPES[number];
export type Stage = typeof STAGES[number];

export type OutreachTarget = {
  id: string;
  name: string;
  type: TargetType;
  city: string;
  website: string;
  contactRole: string;
  contactChannel: string;
  valueProp: string;
  nextAction: string;
  nextActionDate: string;
  stage: Stage;
  fit: number;
  access: number;
  trust: number;
  readiness: number;
  score: number;
  learners: number;
  notes: string;
};

export const SEED_TARGETS: OutreachTarget[] = [
  { id:"flss-vnu", name:"THPT Chuyên Ngoại ngữ – ĐHQGHN", type:"School", city:"Hà Nội", website:"https://flss.vnu.edu.vn/", contactRole:"Ban giám hiệu / Tổ tiếng Anh", contactChannel:"Website trường", valueProp:"Diagnostic chuẩn hóa giúp học sinh chuyên ngữ nhìn rõ gap từng kỹ năng và tạo insight học thuật cho nhà trường.", nextAction:"Tìm Head of English hoặc đầu mối ngoại khóa; xin warm intro qua alumni.", nextActionDate:"Tuần 1", stage:"Qualified", fit:25, access:21, trust:24, readiness:24, score:94, learners:0, notes:"Nguồn chính thức xác nhận tuyển sinh và định vị chuyên ngoại ngữ." },
  { id:"ptnk-vnuhcm", name:"Phổ thông Năng khiếu – ĐHQG-HCM", type:"School", city:"TP.HCM", website:"https://ptnk.edu.vn/", contactRole:"Ban giám hiệu / Tổ tiếng Anh", contactChannel:"Website trường", valueProp:"Báo cáo diagnostic theo cohort hỗ trợ học sinh học thuật mạnh chuẩn bị hồ sơ đại học quốc tế.", nextAction:"Xác minh đầu mối English / career counseling và đề xuất pilot 100 học sinh.", nextActionDate:"Tuần 1", stage:"Qualified", fit:25, access:20, trust:25, readiness:24, score:94, learners:0, notes:"Ưu tiên rất cao; cần personalization theo outcomes du học." },
  { id:"vinschool", name:"Hệ thống Giáo dục Vinschool", type:"School", city:"Toàn quốc", website:"https://vinschool.edu.vn/en/admissions/admissions-announcement/", contactRole:"Academic Partnerships / English Program", contactChannel:"Hotline & admissions email công khai", valueProp:"Diagnostic quy mô lớn, dashboard cohort và benchmark kỹ năng cho học sinh THCS–THPT.", nextAction:"Map central academic team trước khi tiếp cận từng campus.", nextActionDate:"Tuần 2", stage:"Qualified", fit:24, access:20, trust:24, readiness:25, score:93, learners:0, notes:"Hệ thống 61 campus; tiềm năng scale sau pilot nhỏ." },
  { id:"vietabroader", name:"VietAbroader", type:"Community", city:"Toàn quốc", website:"https://vietabroader.org/", contactRole:"Community / Program Lead", contactChannel:"Website & social channels", valueProp:"Diagnostic miễn phí là utility hữu ích cho cộng đồng học bổng, kèm workshop đọc kết quả và action plan.", nextAction:"Đề xuất co-host Diagnostic Week cho học sinh đang chuẩn bị du học.", nextActionDate:"Tuần 1", stage:"Qualified", fit:24, access:23, trust:24, readiness:21, score:92, learners:0, notes:"Community-led nonprofit; value-first và phi thương mại phải rõ." },
  { id:"aiesec-vietnam", name:"AIESEC in Vietnam", type:"Community", city:"Toàn quốc", website:"https://www.aiesec.vn/ve-chung-toi", contactRole:"National Partnerships / YouthSpeak", contactChannel:"aiesec.vietnam@aiesec.net", valueProp:"Diagnostic + learning challenge hỗ trợ năng lực tiếng Anh cho youth leadership pipeline.", nextAction:"Pitch national partnership hoặc một local committee để chạy pilot nhanh.", nextActionDate:"Tuần 1", stage:"Qualified", fit:22, access:24, trust:23, readiness:22, score:91, learners:0, notes:"Có contact công khai và footprint tại nhiều đại học." },
  { id:"ybox", name:"YBOX.VN", type:"Community", city:"Toàn quốc", website:"https://ybox.vn/hop-tac/hop-tac-cung-ybox-227087", contactRole:"Partnership / Media Sponsorship", contactChannel:"Partnership email công khai", valueProp:"Learning challenge tạo utility cho người trẻ và một data story về gap IELTS tại Việt Nam.", nextAction:"Viết one-page co-marketing proposal; tách rõ free community activation khỏi commercial offer.", nextActionDate:"Tuần 1", stage:"Qualified", fit:23, access:24, trust:23, readiness:21, score:91, learners:0, notes:"Có quy trình hợp tác và bảo trợ truyền thông công khai." },
  { id:"fulbright-engagement", name:"Fulbright Student Engagement", type:"University", city:"TP.HCM", website:"https://fulbright.edu.vn/student-engagement/", contactRole:"Student Engagement / Student Council", contactChannel:"engagement@fulbright.edu.vn", valueProp:"Diagnostic + workshop peer learning cho cộng đồng học sinh, sinh viên có định hướng quốc tế.", nextAction:"Tiếp cận Student Engagement với format campus challenge.", nextActionDate:"Tuần 2", stage:"Research", fit:22, access:24, trust:24, readiness:20, score:90, learners:0, notes:"Có đầu mối Student Engagement công khai." },
  { id:"olympia-school", name:"The Olympia Schools", type:"School", city:"Hà Nội", website:"https://theolympiaschools.edu.vn/en", contactRole:"University & Career Counseling / English", contactChannel:"info@theolympiaschools.edu.vn", valueProp:"Diagnostic và sample learner report bổ sung cho university counseling, giúp học sinh tự chủ hơn trong kế hoạch IELTS.", nextAction:"Personalize theo University & Career Counseling; xin call 20 phút.", nextActionDate:"Tuần 1", stage:"Qualified", fit:24, access:23, trust:22, readiness:20, score:89, learners:0, notes:"Website nêu rõ counseling là một phần trải nghiệm học sinh." },
  { id:"hn-ams", name:"THPT Chuyên Hà Nội – Amsterdam", type:"School", city:"Hà Nội", website:"https://www.hn-ams.edu.vn/", contactRole:"Ban giám hiệu / CLB học sinh / Tổ tiếng Anh", contactChannel:"Website trường", valueProp:"Diagnostic challenge cho nhóm học sinh ambition cao; có thể tạo benchmark và insight content.", nextAction:"Tìm alumni warm intro và một student club phù hợp để giảm friction.", nextActionDate:"Tuần 2", stage:"Research", fit:25, access:18, trust:24, readiness:21, score:88, learners:0, notes:"Ưu tiên warm intro hơn cold email." },
  { id:"wellspring-hanoi", name:"Wellspring Hanoi", type:"School", city:"Hà Nội", website:"https://tuyensinh.wellspring.edu.vn/tuyensinh", contactRole:"Academic / Student Services", contactChannel:"Admissions channel", valueProp:"Diagnostic experience bổ sung cho lộ trình tiếng Anh và tạo dữ liệu sẵn sàng IELTS theo khối.", nextAction:"Xác minh người phụ trách secondary English và đề xuất cohort pilot.", nextActionDate:"Tuần 2", stage:"Research", fit:23, access:22, trust:21, readiness:21, score:87, learners:0, notes:"Trường song ngữ, fit tốt nhưng cần tránh pitch như vendor luyện thi." },
  { id:"rmit-student-life", name:"RMIT Vietnam Student Life", type:"University", city:"Hà Nội & TP.HCM", website:"https://www.rmit.edu.vn/students/campus-life", contactRole:"Student Life / Student Council", contactChannel:"Student Connect", valueProp:"Workshop diagnostic dành cho student volunteers hoặc community programs hướng tới học sinh THPT.", nextAction:"Map club hoặc volunteering program có access tới học sinh THPT.", nextActionDate:"Tuần 3", stage:"Research", fit:20, access:22, trust:23, readiness:21, score:86, learners:0, notes:"Có mạng lưới clubs và hoạt động cộng đồng." },
  { id:"vinuni-clubs", name:"VinUniversity Student Clubs", type:"University", city:"Hà Nội", website:"https://vinuni.edu.vn/vi/student_life/cac-cau-lac-bo-va-to-chuc-sinh-vien/", contactRole:"Student Affairs / Club Leaders", contactChannel:"Official club channels", valueProp:"Co-create learning challenge với CLB để kết nối mentor sinh viên và học sinh THPT.", nextAction:"Chọn 2 CLB có mission education/community và tìm direct contact.", nextActionDate:"Tuần 3", stage:"Research", fit:21, access:22, trust:23, readiness:20, score:86, learners:0, notes:"Nên đi qua club cụ thể thay vì central university pitch." },
  { id:"emasi", name:"Hệ thống trường EMASI", type:"School", city:"TP.HCM", website:"https://www.emasi.edu.vn/academy/", contactRole:"English Program / EMASI Academy", contactChannel:"academy@emasi.edu.vn", valueProp:"Diagnostic cho học sinh 12–18 tuổi, kết nối trực tiếp với chương trình English và IELTS hiện có.", nextAction:"Pitch Academy lead với pilot một campus, kèm sample cohort report.", nextActionDate:"Tuần 2", stage:"Qualified", fit:23, access:23, trust:20, readiness:18, score:84, learners:0, notes:"Đầu mối công khai rõ; có chương trình tiếng Anh thiếu niên." },
  { id:"ssis", name:"Saigon South International School", type:"School", city:"TP.HCM", website:"https://www.ssis.edu.vn/parent-portal/contacts", contactRole:"HS Counseling / Community Engagement", contactChannel:"Public school directory", valueProp:"Independent diagnostic + learner reflection workshop cho students chuẩn bị university pathway.", nextAction:"Approach Community Engagement hoặc HS Counseling, không đi qua admissions.", nextActionDate:"Tuần 3", stage:"Research", fit:20, access:24, trust:22, readiness:16, score:82, learners:0, notes:"Contact roles công khai; offer cần phù hợp môi trường quốc tế đã có assessment mạnh." },
  { id:"room-to-read", name:"Room to Read Vietnam", type:"NGO", city:"Nhiều tỉnh thành", website:"https://www.roomtoread.org/countries/vietnam/local-information/", contactRole:"Vietnam Program / Partnerships", contactChannel:"info.vn@roomtoread.org", valueProp:"Assessment access cho nhóm learner underserved, với safeguarding và chương trình được đồng thiết kế.", nextAction:"Discovery conversation trước; không pitch pilot đại trà khi chưa hiểu beneficiary fit.", nextActionDate:"Tuần 4", stage:"Research", fit:18, access:23, trust:25, readiness:16, score:82, learners:0, notes:"Trust cao, nhưng cần alignment sâu với mission và độ tuổi." },
  { id:"blue-dragon", name:"Blue Dragon Children’s Foundation", type:"NGO", city:"Hà Nội & TP.HCM", website:"https://www.bluedragon.org/who-we-are/contact-us/", contactRole:"Education Program / Schools Liaison", contactChannel:"info@bdcf.org", valueProp:"Learning support miễn phí cho nhóm trẻ cần cơ hội, triển khai theo tiêu chuẩn safeguarding của tổ chức.", nextAction:"Xin discovery call với education team; xác định learner readiness và constraints.", nextActionDate:"Tuần 4", stage:"Research", fit:17, access:23, trust:25, readiness:16, score:81, learners:0, notes:"Không dùng language thương mại; relationship-first tuyệt đối." },
  { id:"vnexpress-education", name:"VnExpress Giáo dục", type:"Media", city:"Toàn quốc", website:"https://vnexpress.net/giao-duc", contactRole:"Education Editor / Data Journalist", contactChannel:"Editorial contact", valueProp:"Data story về những gap IELTS phổ biến của học sinh Việt Nam sau khi có dataset đủ lớn.", nextAction:"Để nurture; chỉ pitch sau 1,000+ diagnostic attempts và insight rõ.", nextActionDate:"Sau pilot", stage:"Research", fit:20, access:17, trust:24, readiness:17, score:78, learners:0, notes:"Không pitch product launch. Pitch data + public-interest insight." },
  { id:"saigonchildren", name:"Saigon Children’s Charity", type:"NGO", city:"TP.HCM & các tỉnh", website:"https://www.saigonchildren.com/", contactRole:"Education Program / Partnerships", contactChannel:"Website contact", valueProp:"Free readiness assessment có thể bổ sung cho chương trình education-to-employment của youth phù hợp.", nextAction:"Research age cohort, English baseline và safeguarding requirements.", nextActionDate:"Tuần 4", stage:"Research", fit:18, access:20, trust:23, readiness:16, score:77, learners:0, notes:"Chỉ advance khi có clear beneficiary value." },
  { id:"tuoitre-education", name:"Tuổi Trẻ Giáo dục", type:"Media", city:"Toàn quốc", website:"https://tuoitre.vn/giao-duc.htm", contactRole:"Education Editor", contactChannel:"Editorial contact", valueProp:"Một góc nhìn dữ liệu hữu ích cho phụ huynh và học sinh về learning gaps, không phải thông cáo sản phẩm.", nextAction:"Nurture list; chuẩn bị media brief sau cohort report đầu tiên.", nextActionDate:"Sau pilot", stage:"Research", fit:19, access:16, trust:23, readiness:16, score:74, learners:0, notes:"PR asset phụ thuộc chất lượng dữ liệu và methodology." },
  { id:"hoahoctro", name:"Hoa Học Trò", type:"Media", city:"Toàn quốc", website:"https://hoahoctro.tienphong.vn/", contactRole:"Education / Student Editor", contactChannel:"Editorial contact", valueProp:"Learning challenge gần gũi với teen audience, có expert debrief và outcomes thật.", nextAction:"Nurture; thiết kế format editorial-friendly sau pilot đầu.", nextActionDate:"Sau pilot", stage:"Research", fit:20, access:16, trust:20, readiness:16, score:72, learners:0, notes:"Audience fit tốt; chưa phải kênh đầu tiên trước product proof." }
];
