import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const targets = sqliteTable("targets", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  entityType: text("entity_type").notNull().default("Organization"),
  relationshipType: text("relationship_type").notNull().default("Distribution"),
  organization: text("organization").notNull().default(""),
  location: text("location").notNull().default(""),
  audience: text("audience").notNull().default(""),
  audienceSizeEstimate: text("audience_size_estimate").notNull().default(""),
  audienceFit: text("audience_fit").notNull().default(""),
  expertiseArea: text("expertise_area").notNull().default(""),
  platforms: text("platforms").notNull().default(""),
  contentTopics: text("content_topics").notNull().default(""),
  promotionChannel: text("promotion_channel").notNull().default(""),
  organizationType: text("organization_type").notNull().default(""),
  organizationSize: text("organization_size").notNull().default(""),
  decisionMakerRole: text("decision_maker_role").notNull().default(""),
  distributionChannels: text("distribution_channels").notNull().default(""),
  accessToLearners: text("access_to_learners").notNull().default(""),
  engagementQuality: text("engagement_quality").notNull().default(""),
  influenceType: text("influence_type").notNull().default(""),
  partnershipReadiness: text("partnership_readiness").notNull().default(""),
  researchConfidence: text("research_confidence").notNull().default("Low"),
  city: text("city").notNull(),
  website: text("website").notNull().default(""),
  contactRole: text("contact_role").notNull().default(""),
  contactChannel: text("contact_channel").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  contactPhone: text("contact_phone").notNull().default(""),
  contactFormUrl: text("contact_form_url").notNull().default(""),
  preferredContactMethod: text("preferred_contact_method").notNull().default(""),
  contactStatus: text("contact_status").notNull().default("Research needed"),
  valueProp: text("value_prop").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  nextActionDate: text("next_action_date").notNull().default("Chưa đặt"),
  stage: text("stage").notNull().default("Research"),
  fit: integer("fit").notNull().default(15),
  access: integer("access").notNull().default(15),
  trust: integer("trust").notNull().default(15),
  readiness: integer("readiness").notNull().default(15),
  score: integer("score").notNull().default(60),
  learners: integer("learners").notNull().default(0),
  trials: integer("trials").notNull().default(0),
  notes: text("notes").notNull().default(""),
  facebookUrl: text("facebook_url").notNull().default(""),
  linkedinUrl: text("linkedin_url").notNull().default(""),
  warmContactPerson: text("warm_contact_person").notNull().default(""),
  warmContactTeam: text("warm_contact_team").notNull().default(""),
  warmContactNote: text("warm_contact_note").notNull().default(""),
  relationshipStrength: text("relationship_strength").notNull().default("Cold"),
  introductionStatus: text("introduction_status").notNull().default("Not requested"),
  sourceUrls: text("source_urls").notNull().default(""),
  researchSummary: text("research_summary").notNull().default(""),
  advocateType: text("advocate_type").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
});

export const activities = sqliteTable("activities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  targetId: text("target_id").notNull(),
  kind: text("kind").notNull(),
  detail: text("detail").notNull().default(""),
  occurredAt: text("occurred_at").notNull(),
});
